import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import {AppWrapper} from "@/context/index"
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppWrapper>
          <div className="flex rounded-2xl overflow-hidden">
            <Sidebar />
            <div className="h-screen w-[80%] bg-[#0f1241] p-1">
            <div className="h-full bg-[#edf0f7] rounded-2xl p-8">
              <Header />
              {children}
            </div>
            </div>
          </div>
        </AppWrapper>
      </body>
    </html>
  );
}
